apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ssh-bastion.fullname" . }}
  labels:
    {{- include "ssh-bastion.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ssh-bastion.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ssh-bastion.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ssh-bastion.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.sshConfig.forwardingEnabled }}
      volumes:
        - name: ssh-config-script
          configMap:
            name: ssh-config-script
            defaultMode: 0777
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.envOverrides }}
            - name: {{ printf "%s" $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
          ports:
            - name: ssh
              containerPort: 2222
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 2222
          readinessProbe:
            tcpSocket:
              port: 2222
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.sshConfig.forwardingEnabled }}
          volumeMounts:
            - name: ssh-config-script
              mountPath: /etc/cont-init.d/88-enable_forwarding
              subPath: 88-enable_forwarding
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
