{{- if .Values.sshConfig.forwardingEnabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-config-script
data:
  88-enable_forwarding: |
    #!/usr/bin/with-contenv bash
    echo Enabling Tunneling
    sed -i 's@#PermitTunnel no@PermitTunnel yes@' /etc/ssh/sshd_config
    sed -i 's@AllowTcpForwarding no@AllowTcpForwarding yes@' /etc/ssh/sshd_config
{{- end }}
